### ISSUE TITLE
Unable to do connection - invalid port ":xxxx" after host

### ISSUE THREAD

**Issue by URBANsUNITED** [eduardolat/pgbackweb#88]
Hi!

Using latest docker and can't make a connection to my Postgres database:

Error

> goose run: cannot parse `postgresql://NAME:xxxxxx@postgres:5432/pgbackweb?sslmode=disable`: failed to parse as URL (parse "**postgresql://NAME:xxxxi?13=0@postgres:5432/pgbackweb?sslmode=disable": invalid port ":xxxx" after host)**

My compose file:

```
services:
  pgbackweb:
    image: eduardolat/pgbackweb:latest
    ports:
      - "8095:8085" # Access the web interface at http://localhost:8085
    volumes:
      - ./backups:/backups # If you only use S3 destinations, you don't need this volume
    environment:
      PBW_ENCRYPTION_KEY: "xxx" # Change this to a strong key
      PBW_POSTGRES_CONN_STRING: "postgresql://NAME:Axxxxxxx=$$?@postgres:5432/pgbackweb?sslmode=disable"
      TZ: "Europe/Berlin" # Set your timezone, optional
#    depends_on:
#      postgres:
#        condition: service_healthy
    networks:
      - postgres
      
networks:
  postgres:
    name: postgres
```

My password uses $ (shift 4 - dollar sign) , so I know from other postgres connections, I have to do double dollar signs - $$ but even this is not working.

My fault or on programs side?

Thanks

URBANsUNITED
